services:
  - type: web
    name: internship-radar-backend
    env: node
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: PORT
        value: 4000
      - key: NODE_ENV
        value: production
    plan: free
    region: singapore
    autoDeploy: true
